# -*- coding: utf-8 -*-
"""Python for DS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lDkyC2yeNcArooF7E7Pj62XSUDcDP8oB
"""

import numpy as np
import csv



file_path = "/content/sample_data/annex1.csv"

item_codes = []
item_names = []
category_codes = []
category_names = []

with open(file_path, "r", encoding="utf-8") as file:
    reader = csv.reader(file)
    next(reader)

    for row in reader:
        item_codes.append(row[0])
        item_names.append(row[1])
        category_codes.append(row[2])
        category_names.append(row[3])


item_codes = np.array(item_codes)
item_names = np.array(item_names)
category_codes = np.array(category_codes)
category_names = np.array(category_names)



# Unique categories
unique_categories = np.unique(category_names)

# Count items per category
category_counts = {cat: np.sum(category_names == cat) for cat in unique_categories}


print(" CSV LOADED SUCCESSFULLY \n")

print("Total Items:", len(item_codes))
print("Unique Categories:", unique_categories)
print("\nItems per Category:")
for cat, count in category_counts.items():
    print(f"{cat}: {count}")

print("\nPROCESS COMPLETE ")